#!/usr/bin/env bash
#displays Best School 10 times
counter=0;
while [ "$counter" -le 10 ]; do
    if [ "$counter" -ne 9 ]; then
        echo "Best School";
    else
        echo "Hi";
    fi
 counter=$((counter+1));
done
