#!/usr/bin/env bash
#heyyyy
counter=0;
while [ "$counter" -le 9 ]; do
   if [ "$counter" -eq 3 ]; then
	   echo "bad luck";
   elif [ "$counter" -eq 7 ]; then
	   echo "good luck";
   else
           echo "Best School";	 
   fi
counter=$((counter+1))
done
